import { useMemo, useState } from 'react'
import { Bundle, formatMoney } from '../contracts/trip'
import { useTripStorage } from '../hooks/useTripStorage'
interface Expense { id: string; amount: number; currency: string; category: string; payer: string; date: string; note: string }
const validExpenses = (value: unknown): value is Expense[] => Array.isArray(value) && value.every((item) => item && typeof item.id === 'string' && typeof item.amount === 'number' && typeof item.currency === 'string' && typeof item.category === 'string')
export function BudgetPage({ bundle }: { bundle: Bundle }) {
  const expenses = useTripStorage({ tripId: bundle.trip_id, module: 'budget', schemaVersion: 1, fallback: [] as Expense[], validate: validExpenses, legacyKeys: ['golden_trip_budget_memo'], legacyParser: () => [] })
  const [draft, setDraft] = useState<Expense>({ id: '', amount: 0, currency: bundle.budget.currency, category: '其他', payer: '', date: new Date().toISOString().slice(0, 10), note: '' })
  const total = useMemo(() => expenses.value.filter((item) => item.currency === bundle.budget.currency).reduce((sum, item) => sum + item.amount, 0), [bundle.budget.currency, expenses.value])
  const save = () => { if (!draft.amount || draft.amount < 0) return; const item = { ...draft, id: draft.id || `${Date.now()}` }; expenses.setValue(draft.id ? expenses.value.map((current) => current.id === draft.id ? item : current) : [item, ...expenses.value]); setDraft({ id: '', amount: 0, currency: bundle.budget.currency, category: '其他', payer: '', date: new Date().toISOString().slice(0, 10), note: '' }) }
  return <section className="card" aria-label="預算與費用紀錄"><h2>預算與費用紀錄</h2><div className="subcard"><p>平台估算：<strong>{formatMoney(bundle.budget.total)}</strong></p><p>使用者實際紀錄：<strong>{formatMoney({ amount: total, currency: bundle.budget.currency })}</strong></p><p className="muted">實際紀錄只存在本機，不會寫回 Canonical Trip。</p></div><h3>新增實際支出</h3><div className="form-grid"><input aria-label="金額" type="number" min="0" value={draft.amount || ''} onChange={(event) => setDraft({ ...draft, amount: Number(event.target.value) })} placeholder="金額" /><input aria-label="幣別" value={draft.currency} onChange={(event) => setDraft({ ...draft, currency: event.target.value })} /><input aria-label="分類" value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value })} placeholder="分類" /><input aria-label="付款人" value={draft.payer} onChange={(event) => setDraft({ ...draft, payer: event.target.value })} placeholder="付款人" /><input aria-label="日期" type="date" value={draft.date} onChange={(event) => setDraft({ ...draft, date: event.target.value })} /><input aria-label="備註" value={draft.note} onChange={(event) => setDraft({ ...draft, note: event.target.value })} placeholder="備註" /></div><div className="action-row"><button type="button" onClick={save}>{draft.id ? '更新支出' : '新增支出'}</button>{draft.id ? <button type="button" className="secondary-button" onClick={() => setDraft({ id: '', amount: 0, currency: bundle.budget.currency, category: '其他', payer: '', date: new Date().toISOString().slice(0, 10), note: '' })}>取消</button> : null}{expenses.warning ? <span role="status" className="warning-text">{expenses.warning}</span> : null}</div><ul>{expenses.value.map((item) => <li className="expense-row" key={item.id}><span><strong>{item.category}</strong>｜{item.note || '—'}<small className="muted"> {item.date} {item.payer ? `｜${item.payer}` : ''}</small></span><span>{formatMoney({ amount: item.amount, currency: item.currency })} <button type="button" className="secondary-button" onClick={() => setDraft(item)}>編輯</button> <button type="button" className="danger-button" onClick={() => expenses.setValue(expenses.value.filter((current) => current.id !== item.id))}>刪除</button></span></li>)}</ul></section>
}
