import { useMemo, useState } from 'react'
import { JAPANESE_PHRASES } from '../content/japanese-phrases'

export function JapanesePage() {
  const [query, setQuery] = useState(''); const [category, setCategory] = useState('all'); const [message, setMessage] = useState(''); const categories = [...new Set(JAPANESE_PHRASES.map((phrase) => phrase.category))]
  const phrases = useMemo(() => JAPANESE_PHRASES.filter((phrase) => category === 'all' || phrase.category === category).filter((phrase) => `${phrase.japanese} ${phrase.kana} ${phrase.romaji} ${phrase.traditionalChinese}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  const speak = (text: string) => { if (!('speechSynthesis' in window)) { setMessage('此瀏覽器不支援語音，請使用文字或複製功能。'); return }; try { const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'ja-JP'; utterance.onerror = () => setMessage('目前無法播放語音，請使用文字或複製功能。'); window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance) } catch { setMessage('目前無法播放語音，請使用文字或複製功能。') } }
  const copy = async (text: string) => { try { await navigator.clipboard.writeText(text); setMessage('已複製日文。') } catch { setMessage('無法存取剪貼簿，請長按文字複製。') } }
  return <section className="card" aria-label="實用日文"><h2>實用日文</h2><p className="muted">可搜尋日文、假名、羅馬字與中文；語音在瀏覽器本機執行。</p><div className="toolbar"><input aria-label="搜尋日文" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜尋停車、醫院、兒童椅…" /><select aria-label="日文分類" value={category} onChange={(event) => setCategory(event.target.value)}><option value="all">全部分類</option>{categories.map((item) => <option key={item}>{item}</option>)}</select></div>{message ? <p role="status" className="shell-message">{message}</p> : null}<div className="phrase-list">{phrases.map((phrase) => <article className="subcard" key={phrase.id}><h3>{phrase.traditionalChinese}</h3><p className="phrase-japanese">{phrase.japanese}</p><p className="muted">{phrase.kana}<br />{phrase.romaji}</p>{phrase.usageNote ? <small>{phrase.usageNote}</small> : null}<div className="action-row"><button type="button" onClick={() => copy(phrase.japanese)}>複製日文</button><button type="button" className="secondary-button" onClick={() => speak(phrase.japanese)}>播放發音</button></div></article>)}</div></section>
}
