import { useMemo, useState } from 'react'
import { Bundle, DEFAULT_CHECKLIST } from '../contracts/trip'
import { useTripStorage } from '../hooks/useTripStorage'

interface Note { id: string; title: string; content: string; updatedAt: string }
const labels: Record<string, string> = { passport: '護照／身分文件', twn_license: '台灣駕照與國際駕照', insurance: '保險與租車文件', itinerary_print: '行程離線檔', cash_change: '零用金與零錢', child_supplies: '幼兒用品', elder_med: '長輩常用藥', heat_rain: '防曬、防暑與雨具', car_docs: '汽車文件', stroller: '推車', first_aid: '急救用品' }
const validChecklist = (value: unknown): value is Record<string, boolean> => typeof value === 'object' && value !== null && Object.values(value).every((item) => typeof item === 'boolean')
const validNotes = (value: unknown): value is Note[] => Array.isArray(value) && value.every((item) => item && typeof item.id === 'string' && typeof item.title === 'string' && typeof item.content === 'string')
export function PackingPage({ bundle }: { bundle: Bundle }) {
  const checklist = useTripStorage({ tripId: bundle.trip_id, module: 'checklist', schemaVersion: 1, fallback: DEFAULT_CHECKLIST, validate: validChecklist, legacyKeys: ['golden_trip_checklist'], legacyParser: (raw) => { try { const value = JSON.parse(raw); return validChecklist(value) ? value : null } catch { return null } } })
  const notes = useTripStorage({ tripId: bundle.trip_id, module: 'notes', schemaVersion: 1, fallback: [] as Note[], validate: validNotes, legacyKeys: ['golden_trip_notes'], legacyParser: (raw) => { try { const value = JSON.parse(raw); return typeof value === 'string' ? [{ id: `${Date.now()}`, title: '舊版備忘', content: value, updatedAt: new Date().toISOString() }] : null } catch { return null } } })
  const [draft, setDraft] = useState<Note>({ id: '', title: '', content: '', updatedAt: '' })
  const progress = useMemo(() => { const entries = Object.values(checklist.value); const done = entries.filter(Boolean).length; return `${done}/${entries.length}（${entries.length ? Math.round(done / entries.length * 100) : 0}%）` }, [checklist.value])
  const saveNote = () => { if (!draft.title.trim() && !draft.content.trim()) return; const item = { ...draft, id: draft.id || `${Date.now()}`, title: draft.title.trim() || '未命名備忘', updatedAt: new Date().toISOString() }; notes.setValue(draft.id ? notes.value.map((note) => note.id === draft.id ? item : note) : [item, ...notes.value]); setDraft({ id: '', title: '', content: '', updatedAt: '' }) }
  return <section className="card" aria-label="行李與備忘"><h2>行李、備忘與本機資料</h2><p className="muted">只保存在此瀏覽器：{bundle.title}｜Checklist 完成：{progress}</p><div className="action-row"><button type="button" onClick={() => checklist.reset(DEFAULT_CHECKLIST)}>重設 checklist</button>{checklist.warning || notes.warning ? <span role="status" className="warning-text">{checklist.warning || notes.warning}</span> : null}</div><ul className="checklist">{Object.entries(checklist.value).map(([key, checked]) => <li key={key}><label><input type="checkbox" checked={checked} onChange={(event) => checklist.setValue({ ...checklist.value, [key]: event.target.checked })} />{labels[key] || key}</label></li>)}</ul><h3>備忘</h3><div className="note-editor"><input aria-label="備忘標題" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} placeholder="標題" /><textarea aria-label="備忘內容" value={draft.content} onChange={(event) => setDraft({ ...draft, content: event.target.value })} placeholder="例如：晚到時通知住宿方" /><div className="action-row"><button type="button" onClick={saveNote}>{draft.id ? '更新備忘' : '新增備忘'}</button>{draft.id ? <button type="button" className="secondary-button" onClick={() => setDraft({ id: '', title: '', content: '', updatedAt: '' })}>取消</button> : null}</div></div><div>{notes.value.map((note) => <article className="subcard" key={note.id}><div className="card-heading"><h3>{note.title}</h3><div className="action-row"><button type="button" className="secondary-button" onClick={() => setDraft(note)}>編輯</button><button type="button" className="danger-button" onClick={() => notes.setValue(notes.value.filter((item) => item.id !== note.id))}>刪除</button></div></div><p>{note.content}</p></article>)}</div></section>
}
